<?xml version="1.0" encoding="utf-8"?><Database Name="dnndev_v902.me" Class="Linq_kk_aj_LogDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=dnndev_v902.me;Persist Security Info=True;User ID=dnndev_v902.me" SettingsObjectName="KulturkatalogenLog.My.MySettings" SettingsPropertyName="dnndev_v902_meConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.kk_aj_tbl_Log" Member="kk_aj_tbl_Logs">
    <Type Name="kk_aj_tbl_Log">
      <Column Name="logid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="logtyp" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="arrid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="beskrivning" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="datum" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="changebyuserid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="currenttimestamp" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
    </Type>
  </Table>
  <Table Name="dbo.kk_aj_tbl_Arrangemang" Member="kk_aj_tbl_Arrangemangs">
    <Type Name="kk_aj_tbl_Arrangemang">
      <Column Name="arrid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Rubrik" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
</Database>