<?xml version="1.0" encoding="utf-8"?><Database Name="dnndev_v902.me" Class="Linq_kk_aj_LogDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=dnndev_v902.me;Persist Security Info=True;User ID=dnndev_v902.me" SettingsObjectName="KulturkatalogenLog.My.MySettings" SettingsPropertyName="dnndev_v902_meConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.kk_aj_tbl_Log" Member="kk_aj_tbl_Logs">
    <Type Name="kk_aj_tbl_Log">
      <Column Name="logid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="logtypid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="arrid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="beskrivning" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="datum" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="statusid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="changebyuserid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="currenttimestamp" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
    </Type>
  </Table>
  <Table Name="dbo.kk_aj_tbl_Arrangemang" Member="kk_aj_tbl_Arrangemangs">
    <Type Name="kk_aj_tbl_Arrangemang">
      <Column Name="ArrID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ArrangemangstypID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KonstformID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UtovarID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdminuserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ArrangemangStatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Datum" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Publicerad" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="LookedAt" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="VisningsPeriod" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.kk_aj_tbl_arridtoContent" Member="kk_aj_tbl_arridtoContents">
    <Type Name="kk_aj_tbl_arridtoContent">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="arrid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="contentid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Version" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="datum" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.kk_aj_tbl_content" Member="kk_aj_tbl_contents">
    <Type Name="kk_aj_tbl_content">
      <Column Name="Contentid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Rubrik" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Underrubrik" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ContentText" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="ImageUrl" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="ImageFilename" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ImageSize" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ImageAlt" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="ImageFotograf" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MovieClipUrl" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="MovieClipFilename" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MovieClipSize" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MovieClipAlt" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="MovieClipCredits" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="datum" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.kk_aj_tbl_fakta" Member="kk_aj_tbl_faktas">
    <Type Name="kk_aj_tbl_fakta">
      <Column Name="faktaid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="arrid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="faktatypid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="faktaValue" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsSuperUser" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AffiliateId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="DisplayName" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="UpdatePassword" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastIPAddress" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedOnDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastModifiedByUserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastModifiedOnDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PasswordResetToken" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="PasswordResetExpiration" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LowerEmail" Type="System.String" DbType="NVarChar(256)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.kk_aj_tbl_Utovare" Member="kk_aj_tbl_Utovares">
    <Type Name="kk_aj_tbl_Utovare">
      <Column Name="UtovarID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Organisation" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Fornamn" Type="System.String" DbType="NVarChar(70)" CanBeNull="true" />
      <Column Name="Efternamn" Type="System.String" DbType="NVarChar(70)" CanBeNull="true" />
      <Column Name="Telefonnummer" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Adress" Type="System.String" DbType="NVarChar(70)" CanBeNull="true" />
      <Column Name="Postnr" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Ort" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="Epost" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Kommun" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="Hemsida" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Ovrigt" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.kk_aj_proc_GetArrby_ArrStatus" Method="kk_aj_proc_GetArrby_ArrStatus">
    <Parameter Name="arrStatusTyp" Type="System.Int32" DbType="Int" />
    <Parameter Name="rolltypAdmin" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll1" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll2" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll3" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll4" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll5" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll6" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll7" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll8" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll9" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll10" Type="System.Int32" DbType="Int" />
    <Parameter Name="visningsperiod" Type="System.String" DbType="NVarChar(4)" />
    <ElementType Name="kk_aj_proc_GetArrby_ArrStatusResult">
      <Column Name="ArrID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Datum" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Rubrik" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="UnderRubrik" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Publicerad" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="LookedAt" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="ArrangemangStatus" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="arrangemangtyp" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="konstform" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Organisation" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.kk_aj_proc_GetArrby_Search" Method="kk_aj_proc_GetArrby_Search">
    <Parameter Name="searchval" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="arrStatusTyp" Type="System.Int32" DbType="Int" />
    <Parameter Name="rolltypAdmin" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll1" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll2" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll3" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll4" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll5" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll6" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll7" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll8" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll9" Type="System.Int32" DbType="Int" />
    <Parameter Name="roll10" Type="System.Int32" DbType="Int" />
    <Parameter Name="visningsperiod" Type="System.String" DbType="NVarChar(4)" />
    <ElementType Name="kk_aj_proc_GetArrby_SearchResult">
      <Column Name="ArrID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Datum" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Rubrik" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Underrubrik" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Publicerad" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="LookedAt" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="ArrangemangStatus" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="konstform" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Organisation" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.kk_aj_proc_getlog" Method="kk_aj_proc_getlog">
    <Parameter Name="typ" Type="System.Int32" DbType="Int" />
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="kk_aj_proc_getlogResult">
      <Column Name="logid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="logtyp" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="statustyp" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="beskrivning" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="datum" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="arrid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="logtypid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="statusid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="changebyuserid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Rubrik" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Underrubrik" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ContentText" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Version" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Organisation" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="UtovarID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>